### ISSUE TITLE
Upgrade sigs.k8s.io/controller-runtime version

### ISSUE THREAD

**Issue by HarisChoudhary** [nukleros/operator-builder#72]
The controller-runtime package being used is significantly behind, what is current. v0.13.1 vs v0.18.0
An upgrade would require changes to code generation as some contracts between api's break with the upgrade.

**Comment by scottd018** [comment]
@HarisChoudhary this should be fixed in https://github.com/nukleros/operator-builder/commit/ded0a2be2e74d80d1ea490906df3dc48cf0d23d7 (v0.17.3).  We haven't released a new version just yet, but we can if needed.  Let me know if that commit satisfies what you need and I can close this out, otherwise we can re-update the controller-runtime package.
